[package]
name = "cranelisp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.1.3"
clap = "3.0.0-beta"
#cranelift = "0.78.0"
#cranelift-module = "0.78.0"
#cranelift-jit = "0.78.0"
env_logger = "0.9"
log = "0.4"
rustyline = "9.0.0"
rustyline-derive = "0.5.0"
somok = "1.0.0"
#target-lexicon = "0.12.2"
thiserror = "1.0"

[features]
