[package]
name = "cl-debugger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.17"
cranelisp = { path = "../" }
somok = "1.2.0"
once_cell = "1.9.0"
